image:
  name: "token-janitor"
  tag: "no-version"
  pullPolicy: IfNotPresent

job:
  namespace: "pir-intrusion-detection"
  name: "token-janitor"
  schedule: "0 10 1 * *"
  restartPolicy: Never
  backoffLimit: 3

config:
  name: "token-janitor-config-map"
  firebaseDatabaseURL: "https://<name>.<region>.firebasedatabase.app/"
  googleCloudProjectId: "best-project-ever"

secret:
  name: "token-janitor-secret"
  secretManagerCredential: "credential-json-in-base64"
