apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Values.job.namespace }}
data:
  FIREBASE_DB_URL: '{{ .Values.config.firebaseDatabaseURL }}'
  GCP_PROJECT_ID: '{{ .Values.config.googleCloudProjectId }}'
