apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Values.job.namespace }}
  name: {{ .Values.job.name }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.job.name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.name }}
            - secretRef:
                name: {{ .Values.secret.name }}
      restartPolicy: {{ .Values.job.restartPolicy }}
  backoffLimit: {{ .Values.job.backoffLimit }}
